version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './public_html:/var/www/html'
    env_file:
      - .env
    networks:
      - net0

  web:
    image: 'nginx:latest'
    ports:
      - '8084:80'
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./public_html:/var/www/html
    networks:
      - net0
    
  db:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    env_file:
      - .env
    networks:
      - net0

  search:
    image: 'elasticsearch:7.17.7'
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    networks:
      - net0

networks: 
  net0:
    driver: bridge